plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sndmali27.classattendance'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sndmali27.classattendance'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.17.1'
}
